name: "Post Bot 4"

on:
  workflow_dispatch:
  schedule:
    - cron: "52 * * * *"  # Bot 4 posts at 52 minutes past every hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'
      - run: npm ci
      - run: npm run build
      - name: Send post
        run: BOT_INDEX=3 npm run dev
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE_4 }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}