name: "Post Bot 5"

on:
  workflow_dispatch:
  schedule:
    - cron: "57 * * * *"  # Bot 5 posts at 57 minutes past every hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'
      - run: npm ci
      - run: npm run build
      - name: Download images
        uses: actions/download-artifact@v3
        with:
          name: images
      - name: Send post
        run: BOT_INDEX=4 npm start
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE_5 }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}