name: "Post to Bluesky"

on:
  workflow_dispatch:  # allows manual triggers
  schedule:           # adds cron schedule
    - cron: "9 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0' 
      - run: npm ci
      - run: npm run build
      - name: Send post
        run: npm start
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
          BSKY_HANDLE_2: ${{ secrets.BSKY_HANDLE_2 }}
          BSKY_PASSWORD_2: ${{ secrets.BSKY_PASSWORD_2 }}
          BSKY_HANDLE_3: ${{ secrets.BSKY_HANDLE_3 }}
          BSKY_PASSWORD_3: ${{ secrets.BSKY_PASSWORD_3 }}
          BSKY_HANDLE_4: ${{ secrets.BSKY_HANDLE_4 }}
          BSKY_PASSWORD_4: ${{ secrets.BSKY_PASSWORD_4 }}
          BSKY_HANDLE_5: ${{ secrets.BSKY_HANDLE_5 }}
          BSKY_PASSWORD_5: ${{ secrets.BSKY_PASSWORD_5 }}