name: "Post to Bluesky Bot 2"

on:
  workflow_dispatch:
  schedule:
    - cron: "10 * * * *"  # Different minute for each bot

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'
      - run: npm ci
      - run: npm run build
      - name: Send post
        run: npm run start2  # Different start script for each bot
        env:
          BSKY_HANDLE_2: ${{ secrets.BSKY_HANDLE_2 }}
          BSKY_PASSWORD_2: ${{ secrets.BSKY_PASSWORD_2 }}